#!/bin/bash
#SBATCH -N 1
#SBATCH -A pnlp
#SBATCH --job-name=train-a2c-0.0001
#SBATCH --ntasks-per-node=1
#SBATCH --output=logs/output_train_a2c_0.0001_%j.txt
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH -t 96:00:00
#SBATCH --mem 16G
# sends mail when process begins, and
# when it ends. Make sure you difine your email
# address
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=t.jingxiaochen@gmail.com

export PATH="/n/fs/pnlp/runzhey/miniconda3/bin:$PATH"
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
which python
source activate tom_new
#source /n/fs/pnlp/runzhey/miniconda3/etc/profile.d/conda.sh
#conda activate tom_new
which python
cd /n/fs/pnlp/runzhey/cocoa/craigslistbargain

# tom_itentity_test
#bash exp_scripts/rl/train_a2c.sh "_0.0001_0" "--gpuid 0" "--seed 0" "0.0001" 2>&1 | tee logs/output_train_a2c_0.0001_0.log &
#bash exp_scripts/rl/train_a2c.sh "_0.0001_1" "--gpuid 0" "--seed 1" "0.0001" 2>&1 | tee logs/output_train_a2c_0.0001_1.log &
SD_START=0
SD_END=0
if [ $# -eq 1 ];then
  SD_END=$1
elif [ $# -eq 2 ];then
  SD_START=$1
  SD_END=$2
fi

for i in $(seq $SD_START $SD_END)
do
#  echo $(expr $i \* 3 + 1);
  bash exp_scripts/rl/train_a2c.sh "_0.0001_${i}" "--gpuid 0" "${i}" "0.0001" 2>&1 | tee logs/output_train_a2c_0.0001_${i}.log &
done

wait