#!/bin/bash
#SBATCH -N 1
#SBATCH -A pnlp
#SBATCH --job-name=train-uttr-history-tom
#SBATCH --ntasks-per-node=1
#SBATCH --output=logs/output_train_uttr_history_tom_%j.txt
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH -t 96:00:00
#SBATCH --mem 16G
# sends mail when process begins, and
# when it ends. Make sure you difine your email
# address
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=t.jingxiaochen@gmail.com

EXP_NAME="history_tom"
MODEL_NAME="history_tom"
PROJECT_PATH="/n/fs/pnlp/runzhey/"

export PATH="/n/fs/pnlp/runzhey/miniconda3/bin:$PATH"
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
which python
source activate tom_new
which python
cd ${PROJECT_PATH}cocoa/craigslistbargain

# tom_itentity_test
SD_START=0
SD_END=0
if [ $# -eq 1 ];then
  SD_END=$1
elif [ $# -eq 2 ];then
  SD_START=$1
  SD_END=$2
fi

for i in $(seq $SD_START $SD_END)
do
#  echo $(expr $i \* 3 + 1);
  echo "run task #${i}"
  bash exp_scripts/identifier/train_uttr_history_tom.sh "_${i}" "--gpuid 0" "${i}" "0.001" "hard_pmask_7_0" 2>&1 | tee logs/uttr_history_tom_${i}.log &
done

wait