#!/bin/bash
#SBATCH -N 1
#SBATCH -A pnlp
#SBATCH --job-name=train-id-tom
#SBATCH --ntasks-per-node=1
#SBATCH --output=logs/output_train_id_tom_%j.txt
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH -t 96:00:00
#SBATCH --mem 16G
# sends mail when process begins, and
# when it ends. Make sure you difine your email
# address
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=t.jingxiaochen@gmail.com

EXP_NAME="id_tom"
MODEL_NAME="id_tom"
PROJECT_PATH="/n/fs/pnlp/runzhey/"

export PATH="/n/fs/pnlp/runzhey/miniconda3/bin:$PATH"
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
which python
source activate tom_new
which python
cd ${PROJECT_PATH}cocoa/craigslistbargain

# tom_itentity_test
bash exp_scripts/train_id_history_tom.sh "--gpu 0"
