#!/bin/bash
#SBATCH -N 1
#SBATCH -A pnlp
#SBATCH --job-name=train-id
#SBATCH --ntasks-per-node=1
#SBATCH --output=logs/output_train_id_%j.txt
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH -t 96:00:00
#SBATCH --mem 16G
# sends mail when process begins, and
# when it ends. Make sure you difine your email
# address
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=t.jingxiaochen@gmail.com

export PATH="/n/fs/pnlp/runzhey/miniconda3/bin:$PATH"
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
which python
source activate tom_new
#source /n/fs/pnlp/runzhey/miniconda3/etc/profile.d/conda.sh
#conda activate tom_new
which python
cd /n/fs/pnlp/runzhey/cocoa/craigslistbargain

# tom_itentity_test
bash exp_scripts/train_id.sh "--gpu 0"